[package]
name = "rhisto"
description = "A command line utility for histogramification."
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
regex = "1.11"
meval = "0.2"
